### PR TITLE
Make metadata and links required for each group

### PR DESCRIPTION
**Pull request by vbessonov**
This PR makes `metadata` and `links` properties required for each `group`.

### CODE REVIEW

**Comment by HadrienGardeur** [comment]
I'm not so sure about `links`, is there any specific reason why you added them in addition to `metadata`?

There's no requirement for groups to include a `self` link for example.

**Comment by vbessonov** [comment]
@HadrienGardeur, [the spec](https://github.com/opds-community/drafts/blob/master/opds-2.0.md) says the following:
> An OPDS 2.0 Catalog Feed is a collection too, with the following requirements:
> - it must contain a reference to itself using a self link in links

I thought it assumed that the feed _must_ contains `links` as well. But it might meant that the feed _must_ contain a `self` link _only if_ it contains `links`.

**Comment by HadrienGardeur** [comment]
A feed requires a link but that's not the case of a group.

**Comment by vbessonov** [comment]
You're absolutely right. I updated the PR but the name of the branch still has `links` in it. I can delete it and create a new if it's required.

**Pull request merged**
